# 02_install_policy_package_to_device.yml
---
- name: Add model device to FMG and install Policy Package
  hosts: fmg01
  gather_facts: no
  collections:
    - fortinet.fortimanager

  tasks:
    - name: Add policy package to model device
      fmgr_pm_pkg_adom_obj:
        loose_validation: true
        method: set
        url_params:
          adom: root
        params:
          - data:
              name: default
              scope member:
                - name: FGVM020000000000
                  vdom: root
              type: pkg

    - name: Install policy package to model device
      fmgr_securityconsole_install_package:
        loose_validation: true
        method: exec
        params:
          - data:
              adom: root
              pkg: default
              scope:
                - name: FGVM020000000000
                  vdom: root

